ALTER TABLE ACDP.CRIME_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.CRIME_TYPE CASCADE CONSTRAINTS;

CREATE TABLE ACDP.CRIME_TYPE
(
  CRIME_TYPE_ID  NUMBER,
  CRIME_NAME     VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.CRIMINAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.CRIMINAL CASCADE CONSTRAINTS;

CREATE TABLE ACDP.CRIMINAL
(
  CRIMINAL_ID      INTEGER,
  LAST_NAME        VARCHAR2(255 BYTE),
  FIRST_NAME       VARCHAR2(255 BYTE),
  IMAGE_LABEL      VARCHAR2(255 BYTE),
  GENDER           VARCHAR2(1 CHAR),
  ADDRESS          VARCHAR2(255 BYTE),
  STATE_OF_ORIGIN  VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.FIR
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.FIR CASCADE CONSTRAINTS;

CREATE TABLE ACDP.FIR
(
  FIR_ID          INTEGER,
  OFFICER_ID      INTEGER,
  STATION_ID      INTEGER,
  INCIDENT_DATE   DATE,
  INCIDENT_TIME   TIMESTAMP(6),
  INCIDENT_PLACE  VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.PETITIONER
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.PETITIONER CASCADE CONSTRAINTS;

CREATE TABLE ACDP.PETITIONER
(
  PETITIONER_ID  INTEGER,
  FIR_ID         INTEGER,
  NAME           VARCHAR2(255 BYTE),
  ADDRESS        VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.STATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.STATION CASCADE CONSTRAINTS;

CREATE TABLE ACDP.STATION
(
  STATION_ID       INTEGER,
  STATION_NAME     VARCHAR2(255 BYTE),
  STATION_ADDRESS  VARCHAR2(255 BYTE),
  ZONE             VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.VICTIM
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.VICTIM CASCADE CONSTRAINTS;

CREATE TABLE ACDP.VICTIM
(
  VICTIM_ID  INTEGER,
  FIR_ID     INTEGER,
  NAME       VARCHAR2(255 BYTE),
  ADDRESS    VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX ACDP.CRIME_TYPE_PK ON ACDP.CRIME_TYPE
(CRIME_TYPE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.CRIMINAL_PK ON ACDP.CRIMINAL
(CRIMINAL_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.FIR_PK ON ACDP.FIR
(FIR_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.PETITIONER_PK ON ACDP.PETITIONER
(PETITIONER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.STATION_PK ON ACDP.STATION
(STATION_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.VICTIM_PK ON ACDP.VICTIM
(VICTIM_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ACDP.ACCUSED
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.ACCUSED CASCADE CONSTRAINTS;

CREATE TABLE ACDP.ACCUSED
(
  ACCUSED_ID  INTEGER,
  FIR_ID      INTEGER,
  NAME        VARCHAR2(255 BYTE),
  ADDRESS     VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.CASES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.CASES CASCADE CONSTRAINTS;

CREATE TABLE ACDP.CASES
(
  CASE_ID             INTEGER,
  STATION_ID          INTEGER,
  CASE_NAME           VARCHAR2(255 BYTE),
  CASE_STATUS         VARCHAR2(255 BYTE),
  DESCRIPTION         VARCHAR2(255 BYTE),
  FIR_ID              INTEGER,
  STATION_STATION_ID  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.CRIMINALS_CRIME
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.CRIMINALS_CRIME CASCADE CONSTRAINTS;

CREATE TABLE ACDP.CRIMINALS_CRIME
(
  CASE_ID               INTEGER,
  CRIMINAL_ID           INTEGER,
  CRIME_NAME            VARCHAR2(255 BYTE),
  COURT                 VARCHAR2(255 BYTE),
  DATE_OF_CONVICTION    DATE,
  CRIMINAL_CRIMINAL_ID  INTEGER,
  CASES_CASE_ID         INTEGER,
  CRIME_TYPE_ID         INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ACDP.OFFICER
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACDP.OFFICER CASCADE CONSTRAINTS;

CREATE TABLE ACDP.OFFICER
(
  OFFICER_ID  INTEGER,
  STATION_ID  INTEGER,
  NAME        VARCHAR2(255 BYTE),
  RANK        VARCHAR2(255 BYTE),
  PASSWORD    VARCHAR2(255 BYTE),
  USER_LEVEL  INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX ACDP.ACCUSED_PK ON ACDP.ACCUSED
(ACCUSED_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.CASES_PK ON ACDP.CASES
(CASE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.CRIMINALS_CRIME_PK ON ACDP.CRIMINALS_CRIME
(CRIMINAL_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACDP.OFFICER_PK ON ACDP.OFFICER
(OFFICER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ACDP.CRIME_TYPE ADD (
  CONSTRAINT CRIME_TYPE_PK
  PRIMARY KEY
  (CRIME_TYPE_ID)
  USING INDEX ACDP.CRIME_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.CRIMINAL ADD (
  CONSTRAINT CRIMINAL_PK
  PRIMARY KEY
  (CRIMINAL_ID)
  USING INDEX ACDP.CRIMINAL_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.FIR ADD (
  CONSTRAINT FIR_PK
  PRIMARY KEY
  (FIR_ID)
  USING INDEX ACDP.FIR_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.PETITIONER ADD (
  CONSTRAINT PETITIONER_PK
  PRIMARY KEY
  (PETITIONER_ID)
  USING INDEX ACDP.PETITIONER_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.STATION ADD (
  CONSTRAINT STATION_PK
  PRIMARY KEY
  (STATION_ID)
  USING INDEX ACDP.STATION_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.VICTIM ADD (
  CONSTRAINT VICTIM_PK
  PRIMARY KEY
  (VICTIM_ID)
  USING INDEX ACDP.VICTIM_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.ACCUSED ADD (
  CONSTRAINT ACCUSED_PK
  PRIMARY KEY
  (ACCUSED_ID)
  USING INDEX ACDP.ACCUSED_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.CASES ADD (
  CONSTRAINT CASES_PK
  PRIMARY KEY
  (CASE_ID)
  USING INDEX ACDP.CASES_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.CRIMINALS_CRIME ADD (
  CONSTRAINT CRIMINALS_CRIME_PK
  PRIMARY KEY
  (CRIMINAL_ID)
  USING INDEX ACDP.CRIMINALS_CRIME_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.OFFICER ADD (
  CONSTRAINT OFFICER_PK
  PRIMARY KEY
  (OFFICER_ID)
  USING INDEX ACDP.OFFICER_PK
  ENABLE VALIDATE);

ALTER TABLE ACDP.PETITIONER ADD (
  CONSTRAINT PETITIONER_R01 
  FOREIGN KEY (FIR_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);

ALTER TABLE ACDP.VICTIM ADD (
  CONSTRAINT VICTIM_R01 
  FOREIGN KEY (FIR_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);

ALTER TABLE ACDP.ACCUSED ADD (
  CONSTRAINT ACCUSED_R01 
  FOREIGN KEY (FIR_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);

ALTER TABLE ACDP.CASES ADD (
  CONSTRAINT CASES_R01 
  FOREIGN KEY (STATION_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE,
  CONSTRAINT CASES_R02 
  FOREIGN KEY (FIR_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);

ALTER TABLE ACDP.CRIMINALS_CRIME ADD (
  CONSTRAINT CRIMINALS_CRIME_R01 
  FOREIGN KEY (CASE_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE,
  CONSTRAINT CRIMINALS_CRIME_R02 
  FOREIGN KEY (CRIME_TYPE_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE,
  CONSTRAINT CRIMINALS_CRIME_R03 
  FOREIGN KEY (CRIMINAL_CRIMINAL_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);

ALTER TABLE ACDP.OFFICER ADD (
  CONSTRAINT OFFICER_R01 
  FOREIGN KEY (OFFICER_ID) 
  REFERENCES ACDP.
  ENABLE VALIDATE);
